#!/usr/bin/env bash

# Check we've got an email address
if [ -z "${WEB_ROOT}" ]; then
    echo -e "\n\033[31mYou must provide the \$WEB_ROOT variable with the webroot that will be used for these domains\033[0m\n"
    exit 1
fi

# Check we've got an email address
if [ -z "${DOMAINS}" ]; then
    echo -e "\n\033[31mYou must provide the \$DOMAINS variable with a space separated list of domains to get the SSL certificates for\033[0m\n"
    exit 1
fi

# Check we've agrees the Terms of Service
if [ -z "${AGREE_TOS}" ] || [ "${AGREE_TOS}" != "yes" ]; then
    echo -e "\n\033[31mYou must agree the Terms of Service by setting the \$AGREE_TOS environment variable to yes\033[0m\n"
    exit 1
fi

# Check we've got an email address
if [ -z "${LETSENCRYPT_EMAIL}" ]; then
    echo -e "\n\033[31mYou must provide the \$LETSENCRYPT_EMAIL variable to receive notifications regarding certificates\033[0m\n"
    exit 1
fi

DOMAIN_ARGS=`sed "s/ / -d /g" <<<"$DOMAINS"`

# Override the default site with the letsencrypt basic on
if [ -f /etc/nginx/conf.d/default.conf ]
then
    rm /etc/nginx/conf.d/default.conf
fi

# Copy in the setup-certs.conf sites config, replacing the webroot as you go…
#cp /sites/setup-certs.conf /etc/nginx/conf.d/000-setup-certs.conf
sed "s|%webroot%|${WEB_ROOT}|g" /sites/setup-certs.conf > /etc/nginx/conf.d/000-setup-certs.conf


# Make sure the webroot is
mkdir -p ${WEB_ROOT}

CERTBOT_STAGING=${CERTBOT_STAGING:+--staging}

nginx

echo "certbot certonly --non-interactive --agree-tos --email ${LETSENCRYPT_EMAIL} --expand ${CERTBOT_STAGING} --webroot \
    -w ${WEB_ROOT} -d ${DOMAIN_ARGS}"

certbot certonly --non-interactive --agree-tos --email ${LETSENCRYPT_EMAIL} --expand ${CERTBOT_STAGING} --webroot \
    -w ${WEB_ROOT} -d ${DOMAIN_ARGS}

exit 0;